override CXXFLAGS += -I ../.. -W -Wall -std=c++11
LDFLAGS = -lfreeimage

all: MSER-patternspec-cli


meaningfullness-patternspec-cli: meaningfullness-patternspec-cli.o curvature.o
meaningfullness-cli: meaningfullness-cli.o curvature.o